apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${APP_NAME}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app: ${APP_NAME}
    cluster: ${ENV}
    iac: Jenkinsfile
spec:
  project: default
  source:
    repoURL: git@github.com:${GITHUB_USERNAME}/${K8S_MANIFESTS_REPO}.git
    targetRevision: main
    path: k8a/${ENV}
  destination:
    name: ${ARGOCD_CLUSTER_NAME}
    namespace: ${ENV}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: 
    - CreateNamespace=true