FROM  python:slim-bookworm
WORKDIR /app

COPY ./web.py  .
COPY requirements.txt .

RUN apt-get update --no-install-recommends && \
    apt-get install --no-install-recommends -y gcc && \
    pip install --no-cache-dir -r requirements.txt && \
    chown nobody . -R

EXPOSE 8000
ENTRYPOINT  gunicorn -w 4 -b 0.0.0.0:8000 web:app